
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.11.71.7:13306/zentao?characterEncoding=utf8&useSSL=false
    username:
    password:
#  网易邮箱设置 目前可发送163|126 163邮箱需修改host: smtp.163.com
  mail:
    host: smtp.126.com
    port:
    username: shangyuanxsx@126.com
    password:
    protocol: smtp
  config:
    activate:
      on-profile: dev

#微信公众号模版消息设置
#enable可选值 true|false 默认false
wx:
  mp:
    enable: false
    appId:
    secret:
    token:
    aesKey:

#短信息设置
sms:
  enable: false
  provider: com.syzn.sms.service.impl.AliSmsServiceImpl
  access-key:
  secret-key:
  valid-seconds: 1200
  send-interval: 120
  max-sends-per-day: 5

#邮件推送开关
mail:
  enable: true
#消息提前几天提醒设置
duty:
  remain:
    before:
      days: 2